### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by docoleman36** [blockstack/animal-kingdom#428] opened 2019-09-17 21:44 UTC
![image](https://user-images.githubusercontent.com/46629119/65081947-9f556000-d959-11e9-8e59-7f441f3d4ad0.png)

After running npm start ^ this is what happens.

**Comment by moxiegirl** [comment] 2019-09-18 00:14
Hi, @docoleman36 I'm not able to reproduce this error. Can you provide more information please:

- Operating System you are working in (Name/version number)
- Internet Browser you are using (Name/version number)
- Were you using the web or local version of the Blockstack Browser; if local, what version
- What action were you trying to perform when you encountered this problem

**Comment by moxiegirl** [comment] 2019-09-23 03:20
@docoleman36 Closing for now. If you can provide more information please feel free to reopen.

**Closed by moxiegirl** 2019-09-23 03:20 UTC
